---------------role表--------------------------------------------
DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE IF NOT EXISTS `ROLE`(
	`ID` VARCHAR(32) NOT NULL COMMENT 'ID',
	`CREATE_DATE` DATETIME DEFAULT NULL COMMENT '建立时间',
	`MODIFY_DATE` DATETIME DEFAULT NULL COMMENT '修改时间',
	`ROLE` INT DEFAULT NULL COMMENT '具体权限名称,0-超级管理员，1-普通用户，2-开发人员',
	PRIMARY KEY (`ID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;
--------------user表---------------------------------------------
DROP TABLE IF EXISTS `USER`;
CREATE TABLE IF NOT EXISTS `USER`(
	`ID` VARCHAR(32) NOT NULL COMMENT 'ID',
	`CREATE_DATE` DATETIME DEFAULT NULL COMMENT '建立日期',
	`MODIFY_DATE` DATETIME DEFAULT NULL COMMENT '修改日期',
	`USERNAME` VARCHAR(255) NOT NULL COMMENT '昵称',
	`PASSWORD` VARCHAR(255) NOT NULL COMMENT '密码',
	`EMAIL` VARCHAR(255) DEFAULT NULL COMMENT '电子邮箱',
	`ROLE_ID` VARCHAR(32) NOT NULL,
	PRIMARY KEY (`ID`),
	KEY `FK9FC63FA6DAED032` (`ROLE_ID`),
	 UNIQUE KEY `USERNAME` (`USERNAME`),
	 UNIQUE KEY `EMAIL` (`EMAIL`),
	KEY `FK9FC63FA6C7B24C48` (`ROLE_ID`),
	CONSTRAINT `FK9FC63FA6C7B24C48` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;